# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
        fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Mediator/Mediator.csproj

    - name: Build
      run: dotnet build src/Mediator/Mediator.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test tests/Mediator.Tests/Mediator.Tests.csproj --configuration Debug --framework net8.0

    - name: Extract version
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
        
    - name: Pack project
      run: dotnet pack src/Mediator/Mediator.csproj --configuration Release --no-build -o ./nupkgs /p:PackageVersion=${{ steps.get_version.outputs.version }}

    - name: Push to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Release for version ${{ github.ref_name }}.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload NuGet package to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./nupkgs/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
