# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
        fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Mediator/Mediator.csproj

    - name: Build
      run: dotnet build src/Mediator/Mediator.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test tests/Mediator.Tests/Mediator.Tests.csproj --no-build --verbosity normal

    - name: Pack project
      run: dotnet pack src/Mediator/Mediator.csproj --configuration Release --no-build -o ./nupkgs /p:PackageVersion=${{ steps.get_version.outputs.version }}

    - name: Push to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
